# Generated by Django 4.2.3 on 2023-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=60)),
                ('State', models.IntegerField(blank=True, max_length='60')),
                ('CampusID', models.IntegerField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
