# Generated by Django 4.2.3 on 2023-07-06 22:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name_plural': 'University Campus'},
        ),
        migrations.AlterModelManagers(
            name='universitycampus',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='universitycampus',
            name='CampusID',
        ),
        migrations.RemoveField(
            model_name='universitycampus',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='universitycampus',
            name='State',
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='campusID',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='state',
            field=models.TextField(blank=True, max_length='2'),
        ),
    ]
