# Generated by Django 4.2.3 on 2023-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_alter_universitycampus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycampus',
            name='campusID',
            field=models.IntegerField(blank=True, max_length='60'),
        ),
    ]
