# Generated by Django 4.2.3 on 2023-07-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0006_alter_universitycampus_campusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycampus',
            name='campusID',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
